export const FEATURED_CATEGORIES = [
  'Pokémon TCG',
  'Yu-Gi-Oh! TCG',
  'One Piece TCG',
  'TCG Accessories',
  'Figures',
  'Merchandise',
]

export const content = {
  en: {
    home: 'Home',
    shop: 'Shop',
    blog: 'Blog',
    about: 'About',
    contact: 'Contact',
    wishlist: 'Wishlist',
    account: 'Account',
    cart: 'Cart',
    checkout: 'Checkout',
    shipping: 'Shipping',
    returns: 'Returns',
    terms: 'Terms',
    privacy: 'Privacy',
    impressum: 'Impressum',
    categories: 'Categories',
    searchPlaceholder: 'Search products, sets, accessories...',
    heroTitle: 'Premium TCG Store for Collectors & Players',
    heroText:
      'Discover sealed products, accessories, figures, and preorders in a colorful premium shopping experience.',
    shopNow: 'Shop now',
    viewPreorders: 'View preorders',
    featuredCategories: 'Featured categories',
    hotProducts: 'Hot products',
    newArrivals: 'New arrivals',
    preorders: 'Preorders',
    recommended: 'Recommended for you',
    stock: 'Stock',
    releaseDate: 'Release date',
    preorderNow: 'Preorder now',
    addWishlist: 'Add to wishlist',
    addCart: 'Add to cart',
    noProducts: 'No products available yet.',
    newsletterTitle: 'Get restock and preorder updates',
    newsletterText: 'Subscribe to receive product drops, release alerts, and best deals.',
    subscribe: 'Subscribe',
    socialTitle: 'Instagram / Social feed',
    socialSub: 'Latest drops, unboxings, and release previews.',
    accountAccess: 'Account access',
    register: 'Register',
    login: 'Login',
    email: 'Email',
    password: 'Password',
    logout: 'Logout',
    loggedAs: 'Logged in as',
    role: 'Role',
    quickAdmin: 'Admin quick product creation',
    name: 'Name',
    description: 'Description',
    price: 'Price',
    currency: 'Currency',
    quantity: 'Stock quantity',
    preorder: 'Preorder',
    createProduct: 'Create product',
    customerService: 'Customer service',
    legal: 'Legal',
    rights: 'All rights reserved.',
    remove: 'Remove',
    total: 'Total',
    quantityShort: 'Qty',
  },
  de: {
    home: 'Startseite',
    shop: 'Shop',
    blog: 'Blog',
    about: 'Über uns',
    contact: 'Kontakt',
    wishlist: 'Wunschliste',
    account: 'Konto',
    cart: 'Warenkorb',
    checkout: 'Checkout',
    shipping: 'Versand',
    returns: 'Rückgabe',
    terms: 'AGB',
    privacy: 'Datenschutz',
    impressum: 'Impressum',
    categories: 'Kategorien',
    searchPlaceholder: 'Produkte, Sets, Zubehör suchen...',
    heroTitle: 'Premium TCG Shop für Sammler & Spieler',
    heroText:
      'Entdecke versiegelte Produkte, Zubehör, Figuren und Vorbestellungen in einem farbenfrohen Premium-Shop.',
    shopNow: 'Jetzt shoppen',
    viewPreorders: 'Vorbestellungen ansehen',
    featuredCategories: 'Top-Kategorien',
    hotProducts: 'Beliebte Produkte',
    newArrivals: 'Neu eingetroffen',
    preorders: 'Vorbestellungen',
    recommended: 'Empfohlen für dich',
    stock: 'Bestand',
    releaseDate: 'Erscheinungsdatum',
    preorderNow: 'Jetzt vorbestellen',
    addWishlist: 'Zur Wunschliste',
    addCart: 'In den Warenkorb',
    noProducts: 'Noch keine Produkte verfügbar.',
    newsletterTitle: 'Updates zu Restocks & Vorbestellungen',
    newsletterText: 'Erhalte Infos zu Drops, Release-Daten und besten Angeboten.',
    subscribe: 'Abonnieren',
    socialTitle: 'Instagram / Social Feed',
    socialSub: 'Neueste Drops, Unboxings und Release-Previews.',
    accountAccess: 'Konto-Zugang',
    register: 'Registrieren',
    login: 'Anmelden',
    email: 'E-Mail',
    password: 'Passwort',
    logout: 'Abmelden',
    loggedAs: 'Angemeldet als',
    role: 'Rolle',
    quickAdmin: 'Admin Schnell-Erstellung Produkt',
    name: 'Name',
    description: 'Beschreibung',
    price: 'Preis',
    currency: 'Währung',
    quantity: 'Lagerbestand',
    preorder: 'Vorbestellung',
    createProduct: 'Produkt erstellen',
    customerService: 'Kundenservice',
    legal: 'Rechtliches',
    rights: 'Alle Rechte vorbehalten.',
    remove: 'Entfernen',
    total: 'Gesamt',
    quantityShort: 'Menge',
  },
}
